{% set name = "odc-stats" %}
{% set version = "1.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/odc-stats-{{ version }}.tar.gz
  sha256: e7bb82ac4d9f64ad533442e2a40fe042d1ce2aa6306ae3540a5875dc13d1d2c8

build:
  entry_points:
    - odc-stats = odc.stats.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiobotocore
    - botocore
    - click >=8.0.0
    - dask-core
    - datacube
    - distributed
    - numpy
    - odc-cloud
    - odc-algo
    - odc-dscache >=0.2.2
    - odc-io
    - odc-stac
    - pandas
    - pystac >=1.1.0
    - eodatasets3 >=0.22.0
    - toolz
    - tqdm
    - xarray ==2022.3.0
    - ciso8601
    - gdal
    - fsspec >=2022.1.0
    - fiona
    - rasterio >=1.3.2

test:
  imports:
    - odc
  commands:
    - pip check
    - odc-stats --help
  requires:
    - pip

about:
  home: https://github.com/opendatacube/odc-stats/
  summary: Statistical Product Generation Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
