{% set name = "odc-stats" %}
{% set version = "1.0.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6a31d82fea8a971be86ecb69089155d92382e9dd48bed0c994b5309d762c79af

build:
  entry_points:
    - odc-stats = odc.stats.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=51.0.0
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - aiobotocore
    - botocore
    - click >=8.0.0
    - dask-core
    - datacube
    - distributed
    - numpy
    - odc-cloud
    - odc-algo
    - odc-dscache >=0.2.2
    - odc-io
    - odc-stac
    - pandas
    - pystac >=1.1.0
    - eodatasets3 >=0.22.0
    - toolz
    - tqdm
    - xarray >=2023.1.0
    - ciso8601
    - gdal
    - fsspec >=2022.1.0
    - fiona
    - rasterio >=1.3.2

test:
  imports:
    - odc
  commands:
    - pip check
    - odc-stats --help
  requires:
    - pip

about:
  home: https://github.com/opendatacube/odc-stats/
  summary: Statistical Product Generation Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
